#!/bin/bash
# Quick Deploy Script - Deploy backend to Render

echo "🚀 Low Price Tracker - Quick Deploy Script"
echo "=========================================="
echo ""
echo "This script helps you deploy the backend to Render"
echo ""
echo "STEPS:"
echo "1. Go to https://render.com"
echo "2. Sign in with GitHub"
echo "3. Click 'New +' → 'Web Service'"
echo "4. Select this repository: DEVENDRAN-P/sample"
echo "5. Use these settings:"
echo ""
echo "   Name: low-price-tracker-api"
echo "   Environment: Node"
echo "   Build Command: cd server && npm install"
echo "   Start Command: cd server && node index.js"
echo ""
echo "6. Add Environment Variable:"
echo "   FRONTEND_URL=https://lowpricetracker.vercel.app"
echo ""
echo "7. Click 'Create Web Service' and wait for deployment"
echo "8. Copy your backend URL (e.g., https://low-price-tracker-api-xxxxx.onrender.com)"
echo ""
echo "9. Go to Vercel → Your Project Settings → Environment Variables"
echo "10. Update/Add: VITE_API_URL = [your backend URL]"
echo ""
echo "✅ Done! Your app should now work!"
echo ""
read -p "Press Enter when you've deployed the backend..."
